# Site settings
title: whatwhyhow7
email: wangwenhao.rar@gmail.com
url: https://whatwhyhow7.github.io/
baseurl: "/video"
description: "whatwhyhow7's vlog"
keywords: "vlog,video,douyin,guitar,抖音,吉他,弹唱,台球"
meta_author: whatwhyhow7

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
markdown: kramdown
permalink: pretty
